# 1. Base image
FROM node:20-alpine AS builder

# 2. Create app directory
WORKDIR /app

# 3. Install dependencies (only package.json & lockfile)
COPY package*.json ./
RUN npm install --legacy-peer-deps

# 4. Copy source files
COPY . .

# 5. Build the project
RUN npm run build

# --- Production Image ---
FROM node:20-alpine AS production

WORKDIR /app

# Copy only the built files and dependencies
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma

RUN npx prisma generate 

EXPOSE 3002

CMD ["node", "dist/main.js"]
